### ISSUE TITLE
Ruff extension loaded but not running

### ISSUE THREAD

**Issue by Davrosh** [charliermarsh/ruff-vscode#102]
Current version is v2023.2.0 but behaves the same on other versions I have checked.

I have tried installing the VSCode extension and use it for the first time but without success.
Command line ruff is working fine.

This is the console output for the extension:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/31009042/211174035-695e5ef5-e53e-4ab9-86df-050e332bc8e7.png">

`Python extension loaded`

This is the result of running "Ruff: Restart Server"

<img width="249" alt="image" src="https://user-images.githubusercontent.com/31009042/211174016-eb6ac9aa-2d73-47df-b837-39b45d2ce65f.png">

`Command 'Ruff: Restart Server' resulted in an error (t?.environment.getActiveEnvironmentPath is not a function)`

"Ruff: Fix all auto-fixable problems" doesn't seem to be doing anything.

Let me know what other info is needed.

EDIT: typed out the text displayed on the two screenshots above for easier lookup in the future.

**Comment by charliermarsh** [comment]
Thanks for filing! Do you have anything at all in your `settings.json` related to Ruff?

**Comment by Davrosh** [comment]
Thanks for the quick reply!

I started out without anything ruff-related in my `settings.json` and tried to tweak some settings to see if it would work but haven't had much luck.

OS: MacOS Big Sur Version 11.6 (Apple M1)

Also, I have python installed via pyenv (tried several projects opened up with different python versions) and some projects are also using poetry with the virtual environment managed by that (tried switching the active interpreter in my editor but none of them worked).

**Comment by fredrikaverpil** [comment]
I see the same thing when I just open up a new vscode window and drop a standalone python file into it. Meaning, I've got no folder opened.

I posted my vscode settings [here](https://github.com/charliermarsh/ruff-vscode/issues/103), just a moment ago. Let me know if I can provide any other details. This is on macOS.

![image](https://user-images.githubusercontent.com/994357/211309380-aaba2d95-99db-400c-be3e-b1341cf03869.png)
_Here I would've expected ruff warnings, since I have `ALL` enabled._

**Comment by charliermarsh** [comment]
Interesting, I'll test this out today!

**Comment by charliermarsh** [comment]
Awesome, I can reproduce _that_ (failure to start when opening an individual file), hopefully it's the same issue that @Davrosh ran into?

**Comment by charliermarsh** [comment]
I think this is also an error upstream: https://github.com/microsoft/vscode-python-tools-extension-template/issues/66

**Comment by Davrosh** [comment]
Thanks

1. Sorry for asking, but how can I make sure a VSCode project is opened up as a workspace? I have have several projects and they are all in different directories, each directory opened up in a separate window.
(P.S. I don't have the `Waiting for interpreter from python extension` log message from @fredrikaverpil image)

2. @charliermarsh How do I check if the fix #104 fixed my issue prior to the next release? (what is the best approach for me?)

**Comment by charliermarsh** [comment]
Definitely, happy to keep open as long as the issue is unsolved!

One thing you could try is updating to the latest pre-release, which contains the change that I thought _might_ help (`2023.3.10091950`).

**Comment by charliermarsh** [comment]
I am wondering if this is a bug in the underlying extension template (https://github.com/microsoft/vscode-python-tools-extension-template). It's weird that the trace involves `getActiveEnvironment`, which we don't really touch. Do you use the standalone `isort` or `black` extensions? Do they work for you?

**Comment by fredrikaverpil** [comment]
@davrosh can you try creating a brand new vscode/python project?

Like;

```bash
mkdir projx
cd projx
python3 -m venv .venv
source .venv/bin/activate
pip install ruff black
code .
```

Select the .venv folder as the desired Python virtual environment (I think vscode asks you).

Create a new `.py` file and type in something like:

```python
def x():
    return
```

I can see that ruff is linting:

![image](https://user-images.githubusercontent.com/994357/211410401-0039c9a2-81fb-42f9-8000-be91c6aafbde.png)

Make sure you have enabled the vscode-ruff extension and have something like these vscode settings:

```jsonc
{
  "ruff.importStrategy": "fromEnvironment",
  "ruff.args": [
    "--select=ALL"
  ]
}
```

**Comment by fredrikaverpil** [comment]
> I am wondering if this is a bug in the underlying extension template (https://github.com/microsoft/vscode-python-tools-extension-template). It's weird that the trace involves `getActiveEnvironment`, which we don't really touch. Do you use the standalone `isort` or `black` extensions? Do they work for you?

@charliermarsh not sure if this was a question for me. Anyway, I use the standalone ruff/black/isort/etc commands in the terminal when in a vscode project and those always work great for me.

**Comment by mergd** [comment]
Ran into this issue, couldn't find the root cause, but disabling python related extensions (Black, Pylance, Python Debugger), restarting Ruff showed these logs on startup:
```
Ruff client: couldn't create connection to server.
```

Reenabling Pylance and then restarting vsc again fixed this.
