### ISSUE TITLE
Cannot disable autofix

### ISSUE THREAD

**Issue by fredrikaverpil** [charliermarsh/ruff-vscode#103]
I'm having a problem where I always get ruff's autofixes on <kbd>Cmd</kbd>+<kbd>s</kbd>. Can you reproduce this on your side?

### Relevant vscode setup

```jsonc
{
  "ruff.importStrategy": "fromEnvironment",
  "ruff.fixAll": false,
  "ruff.organizeImports": true,
  "ruff.showNotifications": "onError",

  "ruff.args": [
    "--select=ALL",
    "--per-file-ignores=**/tests/*:S101", // use of assert
    "--per-file-ignores=**/tests/*:D103", // missing docstring
    "--per-file-ignores=**/tests/*:ANN201", // missing return-type annotation
    "--ignore=D"
  ],

  "[python]": {
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.formatOnPaste": false, // set false for black
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true,
      "source.fixAll": false
    }
  },
}
```

I have double-checked my project's `.vscode/settings.json` and it does not contain any ruff settings or autofix related settings.

### Relevant sections of `pyproject.toml`:

```toml
[tool.ruff]
src = ["src"]
line-length = 88  # black default
select = [
    "E",  # pycodestyle (supersedes pep8)
    "F",  # pyflakes
    "S",  # flake8-bandit
    "B",  # flake8-bugbear
    "I",  # isort
]
ignore = [
    "E501",  # line too long
    "E722",  # bare except
    "B008",  # Function calls in arguments defaults
    "B904",  # Raise with "from" statement
]

[tool.ruff.per-file-ignores]
"tests/*" = [
    "S101",
    "S105"
]

[tool.ruff.isort]
known-first-party = ["src"]
```

### Ruff versions

In my project's activated venv, this is the ruff version that I expect vscode-ruff to use (because `"ruff.importStrategy": "fromEnvironment"`):

```bash
pip list | grep ruff
ruff                           0.0.215
```

I see the vscode-ruff extension version is at `v2023.2.0`.

### Example code

Before <kbd>Cmd</kbd>+<kbd>s</kbd>, I can see the `RET501` warning:

```python
async def get_db_override():
    """Avoid resetting the db."""
    return None
```

After <kbd>Cmd</kbd>+<kbd>s</kbd>:

```python
async def get_db_override():
    """Avoid resetting the db."""
    return
```

Here, I would've expected ruff _not to_ autofix, because I've specifically instructed it not to.

**Comment by charliermarsh** [comment]
Will test this out today!

**Comment by charliermarsh** [comment]
Ah, I think I see the issue. Your `settings.json` includes `--select=ALL`, and you still have `Organize imports` on-save enabled. So when you save, we're passing in: `ruff --select ALL --select I001 --fix`.

I think it's fair to call that a bug in the plugin. There are ways to fix it trivially, but they won't work for older Ruff versions, so I'll have to hack something together.

**Comment by charliermarsh** [comment]
If you instead use `--config=/path/to/pyproject.toml`, or a user-specific `pyproject.toml`, it'll also solve the problem for you. 

E.g., in `settings.json`:

```json
{
  "ruff.args": [
    "--config=/path/to/pyproject.toml",
  ],
  ...
}
```

And then in `/path/to/pyproject.toml`:

```toml
[tool.ruff]
select = ["ALL"]
ignore = ["D"]
```

**Comment by charliermarsh** [comment]
@fredrikaverpil - This should be fixed in `2023.3.10092041` (with no changes to your settings). Can you try upgrading to that pre-release build, and let me know if it's resolved? Will re-open if not!

**Comment by fredrikaverpil** [comment]
@charliermarsh oh wow, thank you - whatever you did, it totally fixed the my issue! ⚡❤️ 
I did not change any settings, and now I get import sorting automatically, but not the other fixes 👍

**Comment by charliermarsh** [comment]
Great, thank you :)

Yeah, this should now work as expected even with the settings above. The only drawback is it only works for Ruff versions newer than `0.0.209` (where `ALL` was introduced).
