### ISSUE TITLE
Unable to specify ${workspaceFolder} in ruff.args to reference pyproject.toml

### ISSUE THREAD

**Issue by mobiusklein** [charliermarsh/ruff-vscode#111]
Using `v2023.4.0`

While trying to configure the extension to use my project's `pyproject.toml`, I was unable to make `"--config"` point to the correct file.

My configuration in `pyproject.toml`:
```toml
[tool.ruff]
target-version = "py38"
line-length = 120
extend-select = ["D"]
ignore = ["D400", "D204"]
```

When I run `ruff --config ./pyproject.toml path/to/my/file.py`, I do not see D400 and D204 warnings, but I do in VSCode.

When using this VSCode extension configuration:
```json
"ruff.args": [
        "--line-length", "120",
        "--config", "pyproject.toml"
    ],
```
The extension logs:
```
Running Ruff with: ['c:\\Users\\-\\.vscode\\extensions\\charliermarsh.ruff-2023.4.0-win32-x64\\bundled\\libs\\bin\\ruff.exe',
 '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--line-length', '120', '--config', 'pyproject.toml', 
'--stdin-filename', 'c:\\Users\\-\\Dev\\ms_deisotope\\src\\ms_deisotope\\output\\mzml.py']
```
Where the `pyproject.toml` is not given a qualified path. I don't know where exactly that file it's trying to use lives, but its apparently a real file because there is no error message about the file not existing.

When using this VSCode configuration:
```json
    "ruff.args": [
        "--line-length", "120",
        "--config", "${workspaceFolder}/pyproject.toml"
    ],
```
The extension logs
```
Running Ruff with: ['c:\\Users\\-\\.vscode\\extensions\\charliermarsh.ruff-2023.4.0-win32-x64\\bundled\\libs\\bin\\ruff.exe',
 '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--line-length', '120',
 '--config', '${workspaceFolder}/pyproject.toml', 
'--stdin-filename', 'c:\\Users\\-\\Dev\\ms_deisotope\\src\\ms_deisotope\\output\\mzml.py']
error Failed to parse `c:\Users\-\Dev\ms_deisotope\${workspaceFolder}\pyproject.toml`: The system cannot find the path specified. (os error 3)
```
The `Running Ruff` line uses the unqualified path, but the error message reports the qualified path, but retains `${workspaceFolder}` after its expansion, so there is something wrong with the way `${workspaceFolder}` is handled. I just can't tell where that's happening, either in the extension or in VSCode itself.

**Comment by charliermarsh** [comment]
I'm a little surprised that VS Code isn't expanding that. I'll have to look into it. It's possible that we're not expanding environment variables when resolving those arguments from the CLII (though I'm not certain that `${workspaceFolder}` is actually an env var, as opposed to some special thing evaluated by VS Code).

**Comment by mobiusklein** [comment]
Thank you for the quick response.

I'm not sure I was clear, something is expanding `${workspaceFolder}`, it's just expanding it incorrectly.

In my VSCode config, I wrote `"${workspaceFolder}/pyproject.toml"`, but what `ruff` is being told to read is `c:\Users\-\Dev\ms_deisotope\${workspaceFolder}\pyproject.toml`, so the variable is expanded, but not removed from the path.

I tried putting a relative path instead to see if just the presence of a path separator triggered some logic that put the `${workspaceFolder}` into the path in case it wasn't a specific expansion, but that yielded nothing. I tried to search the extension's source code for something that looked like it was doing the expansion, but I don't know VSCode's extension APIs well enough to recognize something that isn't obvious and found nothing that way either.

**Comment by charliermarsh** [comment]
Oh, right, thank you! I'll try to repro this today.

**Comment by charliermarsh** [comment]
I think that putting `${workspaceFolder}` in a setting value isn't supported by VS Code? Unless I'm misunderstanding. I'm looking at this issue: https://github.com/microsoft/vscode/issues/2809.

**Comment by charliermarsh** [comment]
(What you're seeing is that Ruff doesn't try to expand `${workspaceFolder}`, and then treats `${workspaceFolder}/pyproject.toml` as a relative path. So it expands that to an absolute path. On my machine, it's:

```
Error: Failed to parse `/Users/crmarsh/workspace/ruff/${workspaceFolder}/pyproject.toml`: No such file or directory (os error 2)
```

**Comment by charliermarsh** [comment]
There's an issue though with your `pyproject.toml`. We use slightly different semantics for `extend-select` and `extend-ignore`, so you're actually enabling all `D` codes. I'd suggest this:

```toml
[tool.ruff]
target-version = "py38"
line-length = 120
select = ["E", "F", "D"]
ignore = ["D400", "D204"]
```

Here's a comment where I talk a bit more about how this works: https://github.com/charliermarsh/ruff/issues/1838#issuecomment-1381086271

Here's a note in the docs: https://github.com/charliermarsh/ruff#extend-select

So I suspect that changing the config will fix the issue you're seeing in VS Code. I'm not sure why you aren't seeing `D400` and friends when you run Ruff outside of VS Code, though. What version are you running locally?

**Comment by mobiusklein** [comment]
Thank you. Yes, it seems like trying to manage overrides incorrectly was the problem, and not the path itself. Apologies for the misunderstanding.

**Comment by charliermarsh** [comment]
No problem!

**Comment by FeeeeK** [comment]
Why is this closed? The ruff doesn't seem to handle anything in the settings at all. I store all my configs in the same folder and use the environment variable `CONFIG_PATH` in vscode settings (`${env:CONFIG_PATH}`) and it doesn't work either
