### ISSUE TITLE
Ruff not available as default formatter

### ISSUE THREAD

**Issue by niccolomineo** [charliermarsh/ruff-vscode#120]
I am trying to use the suggested setting

```
"editor.defaultFormatter": "charliermarsh.ruff"
```

but I am getting:

![Screenshot 2023-01-29 alle 20 12 14](https://user-images.githubusercontent.com/5409469/215350296-fa39bbff-843c-43af-864a-bd66819189c1.png)

"The 'Ruff' extension is set as formatter but it cannot format 'Python' files"

When clicking on the blue "Configure" button, it's in fact only the Python formatter I am seeing:

![Screenshot 2023-01-29 alle 20 12 18](https://user-images.githubusercontent.com/5409469/215350345-90451130-4755-4114-9386-cb8e4da99aa4.png)

**Comment by charliermarsh** [comment]
I think the docs are wrong, see #112. I need to update that section.

**Comment by charliermarsh** [comment]
Hopefully clearer now: https://github.com/charliermarsh/ruff-vscode/commit/1f299204bb2c6ae95c6911f36c58d6e2dbc6e60a
