### ISSUE TITLE
Update schedule for ruff-vscode?

### ISSUE THREAD

**Issue by LaurensBosscher** [charliermarsh/ruff-vscode#122]
First of all thanks for this amazing project! This has definitely improved our workflow.

We're using ruff-vscode to lint our mono-repo so that instead of having ruff installed separately for all our projects (and having to keep the versions in sync) we just have to install this extension and we're good to go.

Normally this is not an issue but since @charliermarsh is as fast as a developer as this linter runs (serious, I'm very much impressed!), this means that we're missing out on all the new improvements that have been made between the bundled 0.0.206 and latest 0.0.239 release. We could workaround this, by adding ruff to all our projects but if there's a slight time lag between releases the extra hassle of updating and maintaining the ruff version across projects is probably not worth it.

Perhaps it would be possible to add a (rough) expected release schedule to the readme? E.g ruff-vscode will be updated once every 1, 2 or 3 months?

Thanks and keep up the amazing work!

**Comment by charliermarsh** [comment]
Thank you!

I'll update the extension today, and try to decide on some regular release schedule, which I'll post here :)

It's pretty easy for me to ship pre-releases regularly, but shipping a new release just requires a lot of random work that I haven't automated (bump the version, PR, merge, create release, then bump the new pre-release version, PR, merge, etc.) so I've been lazy :joy:

**Comment by charliermarsh** [comment]
Ok, I just shipped `2023.6.0`.

I'll try to update the extension at least once a month, and will set a recurring reminder on my end.
