### ISSUE TITLE
suggested settings when using ms-python.black-formatter already

### ISSUE THREAD

**Issue by matifali** [charliermarsh/ruff-vscode#126]
When we are using `ms-python.black-formatter` as the default formatter what settinsg are suggsted to use ruff?

Current settings are. 
```json
"[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true
  },
  "editor.formatOnSave": true,
  "python.formatting.provider": "none",
```

**Comment by charliermarsh** [comment]
If you want to run Ruff with fixes on-save, something like this:

```json
{
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll": true
    }
  }
}
```

**Comment by matifali** [comment]
Thank you. So this will override black formatting? I am just confused about which of the twp formatters will take precedence.

**Comment by lpasselin** [comment]
The reason why it was failing here is because I am in a devcontainer. The fix is: after rebuilding, must reopen the folder locally, and reopen in devcontainer (without rebuild). Then, both black and ruff extensions work.
