### ISSUE TITLE
ignore settings in pyproject.toml are, uh, ignored

### ISSUE THREAD

**Issue by bigjools** [charliermarsh/ruff-vscode#129]
I have a bunch of `ignore` settings in pyproject.toml, such as:
```
ignore = [
    "D10", # ignore missing docstrings
]
```
And this works for running `ruff` as a CLI tool, but the extension completely ignores this and flags up missing docstrings everywhere (as D102, but D10 is/should be enough to disable the error).

**Comment by charliermarsh** [comment]
Hi! Can you share a bit more on the directory structure? I.e., where's your `pyproject.toml`, and the file you're editing? (Also, do you have any settings configured in VS Code for the Ruff extension?)

**Comment by bigjools** [comment]
Hey there. To answer each in turn:
 - `pyproject.toml` is at the top level
 - the file is at a deeper level, can't remember how many but maybe 2/3 under the top
 - No special settings configured in vscode, no

Let me know if you need any more info!

**Comment by bigjools** [comment]
Phew, I was starting to think it was my setup! I have two almost identical environments for a server/client side split project and only one of them has this problem, but for the life of me I cannot see what could be causing the difference.

**Comment by charliermarsh** [comment]
Blerg, really tough to debug. I'm especially surprised by the `--config` case. Is there any logging in the output console? (Seen below.)

![Screen Shot 2023-03-07 at 6 25 36 PM](https://user-images.githubusercontent.com/1309177/223578388-72a97d58-f374-4645-8957-7ef016363b83.png)

**Comment by Elypha** [comment]
Here's what I see from my console:

![2023-03-08_00-19-38_433](https://user-images.githubusercontent.com/30290883/223586366-acda6f82-af4d-4313-9956-52e519eccc10.png)

I'm curious that the config seems not loaded
```json
    "ruff.args": [
        "--config=E:/Elypha/Documents/data/pyproject.toml"
    ],
    "ruff.path": [
        "E:/scoop/shims/ruffff.exe"
    ],
```
The `--config` isn't among the params. And btw I tried to load a non-existing `ruffff.exe`, but it doesn't seem to matter

**Comment by bigjools** [comment]
Oh man. I just checked mine and looked at the output and it's got nothing at all in the output. Literally nothing there.

I got suspicious, so hovered over the blue lines and it said the error was caused by `flake8`. Then I realised flake8 was still active as the linter! Disabling the linter makes the errors go away.

Do you have plans to integrate Ruff with that linter selection on vscode?

**Comment by charliermarsh** [comment]
> Do you have plans to integrate Ruff with that linter selection on vscode?

Unfortunately it's out of my control (https://github.com/microsoft/vscode-python/discussions/20716).

**Comment by bigjools** [comment]
No worries - hopefully they make it a bit nicer to use. Thanks for the great tool.

**Comment by dheerajck** [comment]
I have the same issue, ruff seems to be ignoring arguments

settings.json
```{
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length=120",
        "--skip-string-normalization"
    ],
    "editor.formatOnSave": true,
    "workbench.colorTheme": "GitHub Dark Default",
    "ruff.args": [
        "--line-length=120",
        "--ignore=E501",
    ]
}```

error logs
```[error] Error: write after end
	at new NodeError (node:internal/errors:371:5)
	at _write (node:internal/streams/writable:319:11)
	at Writable.write (node:internal/streams/writable:334:10)
	at /home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:124471
	at new Promise (<anonymous>)
	at u.write (/home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:124389)
	at m.doWrite (/home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:113996)
	at /home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:113891
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)```

**Comment by dheerajck** [comment]
I have the same issue, ruff seems to be ignoring arguments

settings.json
```
{
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length=120",
        "--skip-string-normalization"
    ],
    "editor.formatOnSave": true,
    "workbench.colorTheme": "GitHub Dark Default",
    "ruff.args": [
        "--line-length=120",
        "--ignore=E501",
    ]
}
```

error logs
```
[error] Error: write after end
	at new NodeError (node:internal/errors:371:5)
	at _write (node:internal/streams/writable:319:11)
	at Writable.write (node:internal/streams/writable:334:10)
	at /home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:124471
	at new Promise (<anonymous>)
	at u.write (/home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:124389)
	at m.doWrite (/home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:113996)
	at /home/username/.vscode/extensions/charliermarsh.ruff-2023.8.0-linux-x64/dist/extension.js:1:113891
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)

```

**Comment by dheerajck** [comment]
I have the same issue, ruff vscode extension seems to be ignoring arguments

settings.json
```
{
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length=120",
        "--skip-string-normalization"
    ],
    "editor.formatOnSave": true,
    "workbench.colorTheme": "GitHub Dark Default",
    "ruff.args": [
        "--line-length=120",
        "--ignore=E501",
    ]
}
```

**Comment by charliermarsh** [comment]
So in my very basic testing, it _is_ respecting arguments with the config provided above. Which suggests it's not totally broken, but instead, maybe has to do with how we propagate settings in certain contexts (e.g., with workspaces).

**Comment by charliermarsh** [comment]
Is everyone here on Windows? I can try setting up a Windows VM for me to test this out.

**Comment by bigjools** [comment]
I don't have the problem any more as described above, since it was PEBKAC. Linux user, anyway, as a data point.

**Comment by charliermarsh** [comment]
PEBKAC is new to me :D

**Comment by dheerajck** [comment]
I am using linux and I have this issue when not using workspace(directly opening a file),
It works fine with workspace(opening files from folder opened in vscode). 
I dont use separate workspace settings.

**Comment by Elypha** [comment]
I'm on winodws and it's broken both working with a dir and working with single files

**Comment by dheerajck** [comment]
I am using Linux and I have this issue when not using workspace(directly opening a file),
It works fine with workspace(opening files from folder opened in vscode).
I dont use separate workspace settings.

I just tried it on Windows and the same issue exist, probably ruff vscode extension is ignoring arguments when a file is opened directly.

**Comment by charliermarsh** [comment]
I'll try this today.

**Comment by charliermarsh** [comment]
Ok I'm able to reproduce the issue when opening files outside of workspaces. (Doesn't explain why @Elypha is seeing this in workspaces, but it's at least one bug to resolve, maybe it'll end up mattering in that case too.)

**Comment by charliermarsh** [comment]
If anyone is able to test, I published a new pre-release `2023.9.10740409` with some improvements to settings.

**Comment by Elypha** [comment]
> If anyone is able to test, I published a new pre-release `2023.9.10740409` with some improvements to settings.

Thanks for the very prompt fix! I can confirm the problems I found earlier have been fixed and it's working now for both dirs and individual files

**Comment by charliermarsh** [comment]
@dheerajck - The issue is that the string can't be broken up, so Ruff avoids flagging it. That is, there's no way to rewrite `"abcd"` to fit a line-length of two, so we skip the violation.

Ruff _will_ flag this:

```py
"ab cd"
```

**Comment by dheerajck** [comment]
Yeah I noticed that behavior when there is a space in the string, 
This decision makes sense, thank you

**Comment by ProFatXuanAll** [comment]
> Oh man. I just checked mine and looked at the output and it's got nothing at all in the output. Literally nothing there.
> 
> I got suspicious, so hovered over the blue lines and it said the error was caused by `flake8`. Then I realised flake8 was still active as the linter! Disabling the linter makes the errors go away.
> 
> Do you have plans to integrate Ruff with that linter selection on vscode?

Man I got a similar issue.
In my case I set `line-length = 120`, and my editor says `line too long (85 > 79 characters) Flake8(E501)`.
I already disabled flake8 linting on vscode and do not have installation of flake8, but stiil this error show up.
Not sure whether this is issue of ruff or not.
Can you share how you disable flake8 for vscode?
