### ISSUE TITLE
How to use a newer version of ruff?

### ISSUE THREAD

**Issue by paul-brenner** [charliermarsh/ruff-vscode#136]
I've been anxiously awaiting the v0.0.250 release. Now that it is out, I'm trying to figure out how either get it running with the fromEnvironment import strategy or by setting the interpreter path. I'm managing to completely fail at both.

I am using pyenv and tried pip installing ruff. It looks for ruff in ~/.pyenv/versions/3.10.4/envs/my_env_name/bin/ and fails because it isn't in there. I tried adding a symlink to where ruff actually was installed at ~/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ruff and no, that was a bad idea because it complains of permissions errors. 

Other ideas like brew installing and pointing to the result of where ruff (/opt/homebrew/bin/ruff) just causes ruff to crash.

Maybe someone else out there also doesn't know the right way to do this and would appreciate guidance either here or in the readme? Sorry if this is painfully simple.

**Comment by charliermarsh** [comment]
I can provide some pointers but I'm also happy to just cut a new release :)

**Comment by paul-brenner** [comment]
Would love a new release, I suspect I'm not the only one excited about this one. That said, I'd still welcome some of those pointers... and I bet if anyone else ever comes across this issue in the future with similar challenges to what I'm hitting they would love to see those pointers as well.

**Comment by charliermarsh** [comment]
If you want to switch to the pre-release channel, I just uploaded a new release that uses v0.0.251:

![Screen Shot 2023-02-21 at 11 08 17 PM](https://user-images.githubusercontent.com/1309177/220519663-c5abb463-236b-4e0f-898c-059971d41ff2.png)

I'll try to cut a release on the main channel tomorrow, and will also try to reply here with some pointers! Just getting late where I am.

**Comment by prullanferragut** [comment]
> Would love a new release, I suspect I'm not the only one excited about this one. That said, I'd still welcome some of those pointers... and I bet if anyone else ever comes across this issue in the future with similar challenges to what I'm hitting they would love to see those pointers as well.

There is the `importStrategy: fromEnvironment` configuration option but I have the feeling it is not clear when reading the README; what kind of pointers where you @charliermarsh  talking about?

**Comment by razzeee** [comment]
Hrm, I'm seeing the vscode extension flagging something ruff 0.0.254 seems fine with. Vscode reports TCH002 and TCH001, if I fix those the cmd will report TCH004.

It's probably due to the current extension using 0.0.252?

**Comment by charliermarsh** [comment]
@razzeee - Yeah that's possible. I can publish a new pre-release version if helpful.

**Comment by charliermarsh** [comment]
In general I do recommend using `importStrategy: fromEnvironment` (which is now the default) -- that'll pick up any Ruff installed in your workspace's virtual environment, or fall back to the bundled version if no workspace-specific Ruff can be found.

**Comment by razzeee** [comment]
> (which is now the default)

means with the next version/in main? Cause the current extension says it's not the default

**Comment by charliermarsh** [comment]
I just cut a new pre-release.
