### ISSUE TITLE
"Organize imports" doesn't respect configured line length

### ISSUE THREAD

**Issue by rabelux** [charliermarsh/ruff-vscode#143]
I have a pyproject.toml file where I set the line-length to be 100.
This is all working but doesn't seem to be respected when sorting imports.

My import before hitting save: (Total length: 81)
```python
from ThisAndThatAutomation import AutomationOfThisCommon, AutomationOfThatCommon
```

My import after hitting save:
```python
from ThisAndThatAutomation import (AutomationOfThatCommon,
                                   AutomationOfThisCommon)
```

My setting file for VSCode:
```
"[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
}
```

**Comment by charliermarsh** [comment]
It looks like your imports are being sorted with `isort` (Ruff doesn't use that import style), can you try disabling the isort extension?

**Comment by rabelux** [comment]
Thanks for your fast reply!
I don't have isort installed. I also disabled black.
Testing on a different computer yielded the same results so I guess it has to be ruff?

My test looked like this:
1. Create new text file
2. Insert the line I posted above (from ThisAndThatAutomation import ...)
3. Save file

I tested with current ruff extension (v2023.8.0) and with the preview version.
VS Code is in version 1.71.2 from about 5 months ago.
Proof that no isort is present:
![grafik](https://user-images.githubusercontent.com/16120882/221429918-0074d22e-8f1f-4f73-9586-fd1aee79fbad.png)

**Comment by charliermarsh** [comment]
Unfortunately I can't reproduce :(

I'm not sure what could be happening -- Ruff should _always_ be formatting imports like: 

```py
from ThisAndThatAutomation import (
    AutomationOfThatCommon,
    AutomationOfThisCommon,
)```

...if they spill past the line length, and that's the behavior I see locally. We don't have the formatting depicted above implemented at all. It _could_ somehow be Ruff but I'm not sure how I would verify that.

Do you still see this behavior if uninstall the Ruff extension?

**Comment by rabelux** [comment]
Ok I figured it out.
You're totally correct, it's not ruff.

It is Microsoft's Python extension that ships with a sorting functionality, which also gets triggered by setting `"source.organizeImports": true`:

![grafik](https://user-images.githubusercontent.com/16120882/221493256-8e508179-2db2-41a5-b761-7dad843739c4.png)

I'll try to find a way to disable that functionality - if that is even possible.

Workauround in the meantime:
![grafik](https://user-images.githubusercontent.com/16120882/221493736-0faff003-b3b0-4054-a8de-3cfcf4fec515.png)

Do you know whether it is possible for the ruff extension to _replace_ the existing sorting script?

**Comment by JonathanPlasse** [comment]
You should update vscode, your version has isort included inside the Python extension.
After the update, the isort extension will be installed by default. After uninstalling it, it should work.

**Comment by rabelux** [comment]
> You should update vscode, your version has isort included inside the Python extension.
After the update, the isort extension will be installed by default. After uninstalling it, it should work.

@JonathanPlasse Thanks, good to know! My company is a bit slow in providing updates but I'll definitely trigger them.
