### ISSUE TITLE
Quick Fix menu: add `noqa: ...` comment to suppress warning

### ISSUE THREAD

**Issue by eggplants** [charliermarsh/ruff-vscode#148]
Like pylance, I would like to add `noqa: ...` comment to the errored line via `Quick Fix` menu.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/42153744/223613087-24acc230-393b-4f7c-8541-59368b17f84f.png">

**Comment by charliermarsh** [comment]
I think we actually do support this on nightly -- I'm not sure if it's been released on the main channel:

![Screen Shot 2023-03-07 at 10 46 51 PM](https://user-images.githubusercontent.com/1309177/223614587-3ea03f0d-13e4-44be-8346-eb9b56015373.png)

**Comment by eggplants** [comment]
I'm using `v2023.8.0`. I'll try nightly one.

**Comment by eggplants** [comment]
Thanks! It works.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/42153744/223615116-88e9d37b-a80a-40cb-817b-5b4e03ff1fd8.png">

**Comment by charliermarsh** [comment]
Woohoo

**Comment by eggplants** [comment]
I overlooked #25
