### ISSUE TITLE
`W191` lint not recognized by VSCode extension

### ISSUE THREAD

**Issue by stinodego** [charliermarsh/ruff-vscode#156]
I have a bunch of `W191` errors on my code (related to [ruff/#3438](https://github.com/charliermarsh/ruff/issues/3438)), that I have ignored in my `pyproject.toml` file using the `ignore` field:

```toml
[tool.ruff]
select = ["W"]
ignore = ["W191"]
```

When running `ruff .`, I get no errors (as expected). However, VSCode still reports a whole lot of `W191` errors. I also get a message about the `ignore` entry:

```"W191" is not one of ["ALL","A","A0","A00","A001","A002",...```

So it looks like this specific lint was not added to the right list / `ruff.schema.json` is not being loaded properly.

This is on `ruff` version `0.0.254` and later (`fromEnvironment` enabled).

**Comment by stinodego** [comment]
Hm, now that I try this again I don't get the error reported anymore, so that's good! The error message on the ignore entry remains though.

**Comment by charliermarsh** [comment]
It might be that our schema is out of date. We have to update it manually in the SchemaStore repo unfortunately in order for it to be respected in pyproject.toml files (and not just ruff.toml files). I’ll double check today.

**Comment by einarwar** [comment]
I had similar problems yesterday and early today with  That was regarding PLC190. `0.0.255` with `fromEnvironment` enabled.

**Comment by charliermarsh** [comment]
Is it with regards to a warning / error message in the `pyproject.toml`? Or the errors not appearing in the code editor itself?

**Comment by stinodego** [comment]
The error message is gone now, so I'll close this issue. Thanks!

@einarwar if you still experience problems, please open a separate issue.
