### ISSUE TITLE
Last line of file duplicated on save

### ISSUE THREAD

**Issue by kgl-ioniq** [charliermarsh/ruff-vscode#158]
When ruff inserts a newline after the imports, it also duplicates the last line in the file. I am using the preview version of ruff in VSCode (0.0.256) on Windows 10. (A quick test shows the same behavior with the release version of 0.0.252.) I have not configured ruff in any way. I have `fixAll` and `organizeImports` set to `true`:

```json
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true
        }
    }
```

For example, the first code block below will turn into the second on save (when ruff is enabled):

```python
import datetime

import pandas as pd

def foo(bar: datetime.date) -> pd.DataFrame:
    return pd.DataFrame()

```

```python
import datetime

import pandas as pd


def foo(bar: datetime.date) -> pd.DataFrame:
    return pd.DataFrame()
    return pd.DataFrame()

```
If there is no final newline, then the code is formatted into this:
```python
import datetime

import pandas as pd


def foo(bar: datetime.date) -> pd.DataFrame:
    return pd.DataFrame()    return pd.DataFrame()
```
If the formatter inserts two lines, then the last two lines are duplicated. The first block turns into the second:
```python
import datetime

import pandas as pd
def foo(bar: datetime.date) -> pd.DataFrame:
    return pd.DataFrame()

```
```python
import datetime

import pandas as pd


def foo(bar: datetime.date) -> pd.DataFrame:
    return pd.DataFrame()
def foo(bar: datetime.date) -> pd.DataFrame:
    return pd.DataFrame()

```
With ruff disabled, the formatting works correctly. 

Please let me know what other information I can provide.

**Comment by JonathanPlasse** [comment]
- Duplicate of #128

**Comment by kgl-ioniq** [comment]
> * Duplicate of [Auto-fixing sometimes leaves junk at the end of a file when the end result is shorter after the fix #128](https://github.com/charliermarsh/ruff-vscode/issues/128)

Thank you! For the life of me, I could not find any similar issues. This is definitely a duplicate of #128. As mentioned there, disabling isort fixes the problem. (I did not realize isort was installed.) I don't think I have anything further to add, so this issue should be closed.

**Comment by charliermarsh** [comment]
All good, thanks for filing such a clear and comprehensive issue.

**Comment by sleijon1** [comment]
Uninstalling isort was the fix for me as well.

**Comment by hamirmahal** [comment]
I just ran into this issue today, and uninstalling `isort` fixed it. Thanks for posting the fix here, Simon and @kgl-ioniq.

**Comment by varunagrawal** [comment]
For posteriority, adding this fix here, which can be added in the workspace `settings.json` file:

```json
"editor.codeActionsOnSave": {
    "source.organizeImports": "never", // Disable isort
    "source.organizeImports.ruff": "explicit"
},
```
