### ISSUE TITLE
how to modify "Ruff(E501) Line too long"

### ISSUE THREAD

**Issue by OZOOOOOH** [charliermarsh/ruff-vscode#172]
I want to modify the Ruff args using setting.json.
I think handling args can be the solution. but i don't know how

![image](https://user-images.githubusercontent.com/61729168/230834669-ea4e8ce0-dd21-498c-9c6d-9eef820715d7.png)

**Comment by SonGokussj4** [comment]
I don't know how to set the line characters but for ignore, I used:
![image](https://user-images.githubusercontent.com/13331858/231000981-e86f1f1b-b120-4302-b4e3-5a8f0747e5f2.png)

Or in `settings.json` of VSCode add:

```
"ruff.args": [
        "--ignore=E501,F401"
    ],
```

**Comment by charliermarsh** [comment]
If you want to change Ruff settings globally, I recommend configuring Ruff via a user-specific `ruff.toml` file. See [here](https://beta.ruff.rs/docs/faq/#how-can-i-disable-ruffs-color-output) in the FAQ. So, e.g., on macOS, create `/Users/Alice/Library/Application Support/ruff/ruff.toml` (using your username in place of `Alice`), with:

```toml
line-length = 100
```

**Comment by charliermarsh** [comment]
You can also do it in `settings.json`, but the set of things you can change is a little more limited:

```json
"ruff.args": [
  "--ignore=E501,F401",
  "--line-length=100"
],
```

**Comment by OZOOOOOH** [comment]
@charliermarsh @SonGokussj4 Thank you!

**Comment by OZOOOOOH** [comment]
@charliermarsh @SonGokussj4 Thank you!

**Comment by farangkao** [comment]
alternative in pyproject.toml:

```
[tool.ruff]
line-length=119
```

**Comment by zulrang** [comment]
> alternative in pyproject.toml:
> 
> ```
> [tool.ruff]
> line-length=119
> ```

The VSCode extension doesn't use your pyproject.toml unfortunately

**Comment by charliermarsh** [comment]
It does respect pyproject.toml! It operates equivalently to the CLI: for every file you open, it'll search for the first `pyproject.toml` file with a `[tool.ruff]` section in the filesystem path, and apply the settings from that TOML file.

**Comment by nilslindemann** [comment]
> ```json
> "ruff.args": [
>   "--ignore=E501,F401",
>   "--line-length=100"
> ],
> ```

Meanwhile, it is `"ruff.lint.args"` instead of `"ruff.args"` (there are two args settings, one for the formatter and one for the linter)

**Comment by charliermarsh** [comment]
@nilslindemann -- Thanks -- `ruff.args` was deprecated in the latest version. It _should_ still be respected if you have it set, but VS Code will mark it as deprecated in the `settings.json`.

**Comment by nilslindemann** [comment]
@charliermarsh Indeed, VS Code explains this beautifully to the user in the settings.json.

I posted this here mainly to point out that there are two types of command line arguments in the visual settings, and the linter setting comes after the formatter setting. I accidentally inserted my `--ignore=E501` setting into the formatter section, and wondered why the linter would still complain :smile:
