### ISSUE TITLE
[Question] how to disable certain rules

### ISSUE THREAD

**Issue by StevenLi-DS** [charliermarsh/ruff-vscode#173]
I'm using ruff via the vscode extension. I image that there must be a way to disable certain rules, such as

```
Module level import not at top of fileRuff(E402)
```

But I could not find any doc on the extension page. I wonder if there should be a settings in which you can disable certain rules in `settings.json` of vscode

```
"ruff.Skip": ["E402"],
```

Btw, should I disable pylance as well?

**Comment by charliermarsh** [comment]
The easiest way, if you want to keep your configuration within VS Code itself, is to set something like this in your `settings.json`:

```json
"ruff.args": [
  "--ignore=E402,E501"
],
```

If you're willing to setup your configuration _outside_ VS Code, I'd recommend creating a personal `ruff.toml` file. See [here](https://beta.ruff.rs/docs/faq/#how-can-i-disable-ruffs-color-output) in the FAQ. So, e.g., on macOS, create `/Users/Alice/Library/Application Support/ruff/ruff.toml` (using your username in place of `Alice`), with:

```toml
ignore = ["E402"]
```
