### ISSUE TITLE
Last line is duplicated when using "source.organizeImports": true

### ISSUE THREAD

**Issue by rfsan** [charliermarsh/ruff-vscode#181]
I have the following `.vscode/settings.json` file

```json
{
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
}
```

and I'm using the following code to test it

```python
import os

def sum_even_numbers(numbers: list[int]) -> int:
    """Given a list of integers, return the sum of all even numbers in the list."""
    os.abort()
    return sum(num for num in numbers if num % 2 == 0)

```

when I save the file one empty line is added above the function (expected behavior) but the line with the return is duplicated.

```python
import os


def sum_even_numbers(numbers: list[int]) -> int:
    """Given a list of integers, return the sum of all even numbers in the list."""
    os.abort()
    return sum(num for num in numbers if num % 2 == 0)
    return sum(num for num in numbers if num % 2 == 0)

```

**Comment by charliermarsh** [comment]
Unfortunately this is a known issue (#128), that actually traces back to a bug in VS Code itself (https://github.com/microsoft/vscode/issues/174295). The workaround is to ensure that isort is disabled, as the bug itself comes from both Ruff and isort attempting to sort imports at once.
