### ISSUE TITLE
Add ruff binary to the PATH automatically?

### ISSUE THREAD

**Issue by ddahan** [charliermarsh/ruff-vscode#187]
I need to use `ruff` command for pre-commit checks. For this, I installed ruff as a Python package, which is located to `/usr/local/bin/ruff`. Everything's fine.

However, I noticed that ruff-vscode comes with its own ruff binary, but it's not accessible in my terminal by default. I think it's because it's located as a non-standard place like `/root/.vscode-server/extensions/` which is not in the PATH.

I think the ruff binary should be installed only once on my project. Is there a way to improve this extension sothat when it's installed, `ruff` command is available out of the box?

Thanks!

**Comment by charliermarsh** [comment]
`ruff-vscode` does bundle its own binary, but I don't think we can install that into other system paths (and I think some users would find that behavior surprising).

I think my recommendation would be to think about it from the other direction: if you have Ruff installed on your global path, then Ruff should prefer _that_ over the bundled version, which is actually how it behaves in practice as long as you have your `importStrategy ` set to `fromEnvironment` set (the default).
