### ISSUE TITLE
Auto-fix applies different settings than specified in local pyproject.toml

### ISSUE THREAD

**Issue by JSchoeck** [charliermarsh/ruff-vscode#195]
Saving a file in VS Code leads to a different outcome than expected.

My setup is very simple:
- ruff extension installed (both latest stable as well as pre-release as of today show same behavior)
- source.py file and pyproject.toml are in the same folder
- fromEnvironment setting turned on in VSC settings
- suggestion from ruff tutorial in VSC settings.json to auto-fix on save, then format with black

Doing:
- Save a file that has single quotes as a new file 

Issue:
- Single quotes get turned into double quotes in the file
- After saving and the auto-fix running, ruff schizophrenically indicates that single quotes are preferred (Q000)

My pyproject.toml (in the same directory as the .py file):
```
[tool.ruff]
target-version = "py39"
line-length = 120
select = ["E", "F", "B", "Q", "W", "I", "N", "ANN", "COM", "C4", "EM", "PT", "SIM", "RUF"]
ignore = ["E501", "ANN101"]
task-tags = ["TODO", "FIXME", "XXX", "BUG", "NOTE"]

[tool.ruff.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "single"
```

How can I debug this? Honestly, I am not sure if I have a wrong environment setup or if it's an issue with ruff or the VSC extension.

What do I need to do, so that the linting messages and the auto-fix are on the same page?

**Comment by charliermarsh** [comment]
I think the issue here might be that if you're using Black, you can't really use Ruff to enforce single-quotes, since those two tools will continuously disagree on what's correct, and attempt to autofix one-another back-and-forth.

**Comment by JSchoeck** [comment]
I thought that as well, but couldn't find a section on quotes or how to confiugre them in the black documentation at first.
But it's right there, just under "[Strings](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings)".

Since I can't find other obvious issues, maybe this was all there is to it, thanks for the comment!

**Comment by charliermarsh** [comment]
Yeah, Black doesn't support single quotes IIRC. Our formatter will _probably_ make quote-style configurable, but we're not yet promising that :)
