### ISSUE TITLE
[Feature idea] Show check summary when the cursor hovers on a `noqa: comment`

### ISSUE THREAD

**Issue by harupy** [charliermarsh/ruff-vscode#25]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/17039389/202835183-93091df6-dfa3-45b0-bd2c-3f0630b89eb1.png">

It's difficult to infer the check summary from the check code (e.g. `C402`). I think it's useful if the ruff extension shows a tooltip describing the check.

**Comment by harupy** [comment]
https://user-images.githubusercontent.com/17039389/202836506-eb486f40-85b1-426c-ab1e-6d7be14f5132.mov

**Comment by charliermarsh** [comment]
Oh nice! Do you want to PR?

**Comment by harupy** [comment]
Yes, filed #26 :)
