### ISSUE TITLE
Pick up `pyproject.toml` based on file path or workspace

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff-vscode#3]

**Comment by TommasoAmici** [comment]
This would be quite useful for me, would you accept a PR implementing it?

**Comment by charliermarsh** [comment]
I wonder how that works, I would've expected it not to since we don't use the passed-in path to infer the project root 🤔

**Comment by charliermarsh** [comment]
Oh, we pass the stdin filename, of course...

**Comment by fredrikaverpil** [comment]
@charliermarsh does this issue mean that the selected rules from pyproject.toml would supersede/take precedence over what you have in your vscode settings?

I don't think this works currently but I would _really_ like to see this.

When working in a team where everyone has individual vscode settings, it's confusing to talk about which ruff rules you want in your project - when you don't see warnings in vscode based on the pyproject.toml for that project.
I also posted about this over at mastodon ([here](https://fosstodon.org/@fredrikaverpil/109641486364180274)).

**Comment by charliermarsh** [comment]
> I don't think this works currently but I would really like to see this.

Yeah, that's correct -- the `pyproject.toml` in the project path _doesn't_ override the settings from the VS Code extension. Which is not ideal, for the reasons you described.

The best way to solve this _today_ is to use a user-specific `pyproject.toml` rather than going through the VS Code extension. For example, if you're on macOS, you can create a `pyproject.toml` at `~/Library/Application\ Support/ruff/pyproject.toml`. Then, when linting, if Ruff can't find a `pyproject.toml` in the current file path, it will use _that_ as the default settings.

**Comment by fredrikaverpil** [comment]
@charliermarsh thanks for this - great that there's this workaround. Is this `pyproject.toml` fallback documented somewhere?
