### ISSUE TITLE
Enable usage from Neovim

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff-vscode#50]
I'm pretty oblivious to what's required here, but the LSP in `./bundled` is entirely VS Code agnostic. How do we enable users to leverage that LSP from Neovim?

**Comment by smackesey** [comment]
I use Neovim so I can help with this. I've been running `ruff` via [diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver), but IIUC this repo implements it's own language server layer over Ruff?

**Comment by charliermarsh** [comment]
Cool, I would love help. The LSP is in the `bundled` subdirectory. I’m guessing that we’ll want to publish that as a standalone package, `pip install` it, and then configure it within Neovim rather than via the VS Code client (all the TyperScript stuff). But I admittedly haven’t explored it deeply yet.

**Comment by charliermarsh** [comment]
There's another LSP coming along in https://github.com/python-lsp/python-lsp-ruff. It works today in Neovim. I wouldn't use it quite yet, there's an issue around parsing configuration files that would likely make it break for you. But in the next few days, it should be ready.

**Comment by charliermarsh** [comment]
Okay, I've now published the LSP as a standalone package on PyPI ([`ruff-lsp`](https://pypi.org/project/ruff-lsp/)).

I've included instructions on how to use it with Neovim [here](https://github.com/charliermarsh/ruff-lsp#example-neovim). It includes Quick Fix and all the other Code Actions supported by the VS Code plugin.

![Screen Shot 2022-12-17 at 9 05 25 PM](https://user-images.githubusercontent.com/1309177/208276254-371b5197-924b-445b-a310-820099de603a.png)
