### ISSUE TITLE
Invalid value PD

### ISSUE THREAD

**Issue by igonro** [charliermarsh/ruff-vscode#71]
I have the following configuration in my `settings.json`:

```json
    "ruff.args": [
        "--line-length=88",
        "--select=F",
        "--select=E",
        "--select=W",
        "--select=C90",
        "--select=I",
        "--select=S",
        "--select=B",
        "--select=A",
        "--select=PD",
        "--select=RUF",
    ],
```

And I get the following error on the Ruff output:

```error: Invalid value 'PD' for '--select <SELECT>': Matching variant not found```

If I remove the `"--select==PD"` line, the error disappears and Ruff works fine.

**Comment by charliermarsh** [comment]
Are you using the bundled version of Ruff? You may need to use PDV for now (instead of PD — the prefix was renamed recently). I can cut a new release tomorrow with a newer version of Ruff.

**Comment by igonro** [comment]
Yes, I'm using the bundled version. I will try with PDV, thanks!

**Comment by igonro** [comment]
With PDV is working. Maybe the docs should be updated to make this clear, but this is in the ruff repo, not this one.

You can close this issue.

**Comment by charliermarsh** [comment]
Okay cool, thank you! When I upgrade, PDV will continue to work (but will emit a deprecation warning).
