### ISSUE TITLE
Make "source.organizeImports": true, to use ruff instead of isort

### ISSUE THREAD

**Issue by ilkersigirci** [charliermarsh/ruff-vscode#76]
```json
{
"[python]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.codeActionsOnSave": {
        // "source.fixAll": true,
        "source.organizeImports": true, 
    },
  },
}
```

By using this configuration, I couldn't make import sorting with `ruff`, instead vscode runs them with `isort` [by default](https://code.visualstudio.com/docs/python/editing#_sort-imports) and there is no configuration to change this. I have checked the `Output` window to make sure of this.

I know I can `Ctrl+Alt+P` -> Organize Import -> Source Action: ruff but I would be good if I am able to configure it in `settings.json`

**Comment by charliermarsh** [comment]
👍 I'm not 100% sure how to configure this but I understand what you're going for and agree it'd be nice. (The other option is to uninstall the `isort` plugging which I'm guessing you don't want to do!)

**Comment by ilkersigirci** [comment]
Thanks for the quick response, actually if I remove `isort` extension from vscode, everything works as expected but since [official vscode python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) comes with `isort` by default, `source.organizeImports` always chooses `isort`.

I think this is counterintuitive for the user to know which sorting mechanism is used

**Comment by charliermarsh** [comment]
Yeah that makes sense. Let me play around with the settings and see if there's a way to make this work by default.

**Comment by charliermarsh** [comment]
I think the recommended way to fix this it add scoped options, like `source.organizeImports.ruff`, similar to what ESLint does with `source.fixAll.eslint`.

https://github.com/microsoft/vscode/issues/90221

**Comment by ilkersigirci** [comment]
Makes sense. I hope the implementation is easy :)

**Comment by charliermarsh** [comment]
I'm learning VS Code extensions as I go, so most things end up being easy in the end but take some time for me to figure out :)

**Comment by charliermarsh** [comment]
I'll throw up a PR anyway.

**Comment by charliermarsh** [comment]
Ok, in theory this is now fixed (in the latest release, building now) with:

```json
{
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.fixAll.ruff": true,
            "source.organizeImports.ruff": true
        }
    }
}
```

But, that might cause the isort extension to error. I've filed an issue in the isort repo: https://github.com/microsoft/vscode-isort/issues/192.
