### ISSUE TITLE
Ruff dies when args are set

### ISSUE THREAD

**Issue by MadameMinty** [charliermarsh/ruff-vscode#90]
Hi, I've encountered an issue.

**Expected:** Ruff parses args and e.g. sets max line length.

**Actual:** Ruff stops linting when any args are defined, starts when they're deleted.

**Reproduction:** define an arg, e.g. `--line-length 104`.

I just tried VSCode Ruff extension `v2022.0.26` and `v2022.1.13621212` (i.e. pre-release) (VSCode `1.75.0-insider`, Windows `10.0.19044`), and decided to add an argument `--line-length 104` in the settings (everything else is default).

The setting copied as JSON loos like this:
```json
"ruff.args": [
  "--line-length 104"
]
```

But then Ruff stops linting, and I see
![image](https://user-images.githubusercontent.com/24495074/209973493-d7418208-1b0f-4c06-a3b0-d52fc4856a04.png)
>FormattingExtension 'Ruff' is configured as formatter but it cannot format 'Python'-files

I'm guessing the process returns a non-zero exit code. It doesn't matter how many arguments I add, or what kind. I tried `line-length`, `ignore`, and `target-version`. Upon removing the last argument, so that the setting copied as JSON loos like this: `"ruff.args": []`, linting immediately resumes.

**Comment by charliermarsh** [comment]
Can you try adding an equals sign between the line-length flag and the value? Or passing the flag and the value as two separate entries in the args array?

**Comment by MadameMinty** [comment]
That works! For a test, I added args `--ignore=E722` and `--line-length=104` and both parsed properly (separately and together) and Ruff didn't die.

For the sake of further testing, adding `--line-length` and `104`  as well as `--ignore` and `E722` also worked.

I tried following the `ruff --help` guide, where there are spaces instead of `=`, and spaces work in my default shell using the bundled binary.

**Comment by charliermarsh** [comment]
Awesome. It has to do with how those arguments are passed to the script via `subprocess`. If you have `["line-length 104"]`, that actually does something like `ruff "--line-length 104"`, so Ruff tries to parse that as a "single" argument.
